### ISSUE TITLE
Priority is too low：(400000000 vs 400000000)

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/darwinia.js#34]
This promise error can not be caught, need auto-restart relayer after this happens.

<details>
<summary>Priority is too low</summary>
<pre><code>
𝝺 dj keep relay
2020-05-07 17:34:35        API/INIT: RPC methods not decorated: balances_usableBalance
Unknown signed extensions CheckEthRelayHeaderHash found, treating them as no-efect
Unknown signed extensions CheckEthRelayHeaderHash found, treating them as no-efect
Unknown types found, no types for ElectionResultT
[ info ]: start from the lastest eth header of darwinia...
Unknown signed extensions CheckEthRelayHeaderHash found, treating them as no-efect
Unknown signed extensions CheckEthRelayHeaderHash found, treating them as no-efect
[ info ]: the next height is 9964568
[ event ]: relay block 9964568 to darwinia...
2020-05-07 17:34:57        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (400000000 vs 400000000): The transaction has too low priority to replace another transaction already in the pool.
2020-05-07 17:34:57             DRR: Error: 1014: Priority is too low: (400000000 vs 400000000): The transaction has too low priority to replace another transaction already in the pool.
    at RpcCoder._checkError (/Users/mercury/code/darwinia.js/node_modules/@polkadot/rpc-provider/coder/index.js:83:13)
    at RpcCoder.decodeResponse (/Users/mercury/code/darwinia.js/node_modules/@polkadot/rpc-provider/coder/index.js:46:10)
    at WsProvider.value (/Users/mercury/code/darwinia.js/node_modules/@polkadot/rpc-provider/ws/Provider.js:160:90)
    at W3CWebSocket.value [as onmessage] (/Users/mercury/code/darwinia.js/node_modules/@polkadot/rpc-provider/ws/Provider.js:140:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/mercury/code/darwinia.js/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/mercury/code/darwinia.js/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/mercury/code/darwinia.js/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.EventEmitter.emit (domain.js:485:12)
    at WebSocketConnection.processFrame (/Users/mercury/code/darwinia.js/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /Users/mercury/code/darwinia.js/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
2020-05-07 17:34:57        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (400000000 vs 400000000): The transaction has too low priority to replace another transaction already in the pool.
(node:66742) UnhandledPromiseRejectionWarning: Error: 1014: Priority is too low: (400000000 vs 400000000): The transaction has too low priority to replace another transaction already in the pool.
    at RpcCoder._checkError (/Users/mercury/code/darwinia.js/node_modules/@polkadot/rpc-provider/coder/index.js:83:13)
    at RpcCoder.decodeResponse (/Users/mercury/code/darwinia.js/node_modules/@polkadot/rpc-provider/coder/index.js:46:10)
    at WsProvider.value (/Users/mercury/code/darwinia.js/node_modules/@polkadot/rpc-provider/ws/Provider.js:160:90)
    at W3CWebSocket.value [as onmessage] (/Users/mercury/code/darwinia.js/node_modules/@polkadot/rpc-provider/ws/Provider.js:140:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/mercury/code/darwinia.js/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/mercury/code/darwinia.js/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/mercury/code/darwinia.js/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.EventEmitter.emit (domain.js:485:12)
    at WebSocketConnection.processFrame (/Users/mercury/code/darwinia.js/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /Users/mercury/code/darwinia.js/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:66742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66742) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</code></pre>
</details>

**Comment by clearloop** [comment]
This is caused by the chain side, reopen if when it's necessary.
