### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia.js#36]
```
promote:~ denny$ dj --version
/Users/denny/.config/yarn/global/node_modules/@darwinia/dj/lib/src/_relay.js:26
class Relay extends util_1.Service {
                           ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/denny/.config/yarn/global/node_modules/@darwinia/dj/lib/src/_relay.js:26:28)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/denny/.config/yarn/global/node_modules/@darwinia/dj/lib/src/relay.js:15:34)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/denny/.config/yarn/global/node_modules/@darwinia/dj/lib/index.js:20:33)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
```

**Comment by clearloop** [comment]
This is caused by the conflict versions of `@darwinia/dj`

```
yarn global remove `@darwinia/dj`
yarn global add `@darwinia/dj`
```

Will fix this.

**Comment by clearloop** [comment]
Please re-open if still have this issue.
