### ISSUE TITLE
Error: FATAL: Unable to initialize the API: createType(EthNetworkType)

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia.js#8]
```
MacBookPro:~ denny$ dj keep relay
[ warn ]: eth secret key has not been configured, edit `~/.darwinia/dj.json` if it is required
Unable to resolve type TsInMs, it will fail on constrution
Unknown types found, no types for BalanceInfo,EthNetworkType,ExposureT,TsInMs
Unable to resolve type EthNetworkType, it will fail on constrution
2020-04-16 18:25:49        API/INIT: Error: FATAL: Unable to initialize the API: createType(EthNetworkType):: Cannot construct unknown type EthNetworkType
    at EventEmitter.value (/Users/denny/.config/yarn/global/node_modules/@darwinia/api/node_modules/@polkadot/api/base/Init.js:67:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
dj keep <service>

trigger services

位置：
  service                           [必需] [可选值: "crash", "relay", "fetcher"]

Options:
  --help, -h     显示帮助信息                                             [布尔]
  --version, -V  显示版本号                                               [布尔]
  --daemon, -d                                            [布尔] [默认值: false]

Error: FATAL: Unable to initialize the API: createType(EthNetworkType):: Cannot construct unknown type EthNetworkType
    at EventEmitter.value (/Users/denny/.config/yarn/global/node_modules/@darwinia/api/node_modules/@polkadot/api/base/Init.js:67:25)
```

**Comment by HackFisher** [comment]
Suppose to work after updating types.json
```
dj config -u
```
