### ISSUE TITLE
TypeError: Cannot read property 'fromRed' of null

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia.js#9]
```
TypeError: Cannot read property 'fromRed' of null
    at Point.getX (/Users/denny/.config/yarn/global/node_modules/elliptic/lib/elliptic/curve/short.js:415:17)
    at Point._encode (/Users/denny/.config/yarn/global/node_modules/elliptic/lib/elliptic/curve/base.js:295:16)
    at Point.encode (/Users/denny/.config/yarn/global/node_modules/elliptic/lib/elliptic/curve/base.js:304:28)
    at KeyPair.getPublic (/Users/denny/.config/yarn/global/node_modules/elliptic/lib/elliptic/ec/key.js:66:19)
    at Object.fromPrivate (/Users/denny/.config/yarn/global/node_modules/web3-eth-accounts/node_modules/eth-lib/lib/account.js:25:34)
    at Accounts.privateKeyToAccount (/Users/denny/.config/yarn/global/node_modules/web3-eth-accounts/src/index.js:124:46)
    at Wallet.add (/Users/denny/.config/yarn/global/node_modules/web3-eth-accounts/src/index.js:474:34)
    at new Web3 (/Users/denny/.config/yarn/global/node_modules/@darwinia/api/lib/src/web3.js:33:36)
    at Object.<anonymous> (/Users/denny/.config/yarn/global/node_modules/@darwinia/api/lib/src/auto.js:32:16)
    at Generator.next (<anonymous>)
    at /Users/denny/.config/yarn/global/node_modules/@darwinia/api/lib/src/auto.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/denny/.config/yarn/global/node_modules/@darwinia/api/lib/src/auto.js:4:12)
    at Object.autoWeb3 (/Users/denny/.config/yarn/global/node_modules/@darwinia/api/lib/src/auto.js:30:12)
    at Function.<anonymous> (/Users/denny/.config/yarn/global/node_modules/@darwinia/dj/lib/src/fetcher.js:78:38)
    at Generator.next (<anonymous>)
```

**Comment by HackFisher** [comment]
After setting the ```eth.secret``` in config, this issue gone, should be related.
